# Generated by Django 4.1.7 on 2023-03-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTimezoneMapping',
            fields=[
                ('store_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('timezone_str', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='storestatusdb',
            name='timestamp_utc',
            field=models.DateTimeField(max_length=6),
        ),
        migrations.CreateModel(
            name='StoreBusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('start_time_local', models.TimeField()),
                ('end_time_local', models.TimeField()),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.storetimezonemapping')),
            ],
        ),
    ]
