# Generated by Django 4.1.7 on 2023-03-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_storetimezonemapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebusinesshours',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, to='monitoring.storetimezonemapping'),
        ),
    ]
