# Generated by Django 4.1.7 on 2023-04-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_storebusinesshours_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebusinesshours',
            name='store_id',
            field=models.CharField(max_length=25),
        ),
    ]
