# Generated by Django 4.1.7 on 2023-04-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_storebusinesshours_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('failed', 'Failed'), ('completed', 'Completed')], default='running', max_length=9)),
            ],
        ),
    ]
